### ISSUE TITLE
Love 11.2 Issues

### ISSUE THREAD

**Issue by MutableLoss** [Ulydev/push#25]
I ran into a few issues with love 11, and thought you would like to know. 

Current version doesn't support the stencil update. This can be remedied by updating the setCanvas calls to include the new stencil key addition:

e.g. **push.lua:83**
```
return love.graphics.setCanvas { self:getCanvasTable(name).canvas, stencil = true }
```
_I made the same addition to the remaining calls_

While I haven't had any issues after this update, I am new to Love and I'm not if there are potential side-effects that they may cause.

The other issue is that getDPIScale on a retina screen is throwing the scaling off (guessing it's returning 4), setting the canvas to scale 25% of the intended size. To get around this, I had to change line 101:

```
self._PSCALE = self._highdpi and 1 -- love.window.getDPIScale() or 1
```

Anyways, loving the library (no pun intended)! 👍

**Comment by Ulydev** [comment]
Hello @3DEsprit, thank you for opening an issue, and sorry for the delay! There is a lot of stuff going on and I don't have much time to check on all of these since I don't use LÖVE much anymore. If you have managed to fix these for your own project, I highly encourage you to contribute to the library and open a pull request, which I'll gladly review. Cheers! :-)

**Comment by MutableLoss** [comment]
Sounds good man! I'll get a PR made this week with an update. 👍

EDIT: Or next week. 😄

**Comment by Ulydev** [comment]
Thanks again for the PR!
